Feature/gemeni cache
CAFECA-IO/AICH pull request #79
Opened 2024-08-15 06:36 UTC by TinyMurky

### DEVELOP

- feat: Gemini 套入 Lru cache 完成 upload, process status, result的三個步驟
  
#### Related Issues

- [X] Issue Number:
    - #76 
    - #77 
    - #78 

#### Checklist

- [x] Used `@` in import paths.
- [x] Verified naming convention compliance ([Naming Convention Guidelines](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md)).
- [x] Coding style verification: checked
- [x] new Library: 0
- [x] new Class / Component: 0
- [x] new loop: 0
- [x] new recursive: 0
- [x] high risk: 0
- [x] new sql: 0

#### UML Diagrams

- None

#### Additional Notes

- Ensured all links are up-to-date.
- Conducted thorough testing on responsive design changes.
- Documented any notable considerations or edge cases addressed.

2024-08-15 12:15 UTC, Luphia requested changes

2024-08-15 12:15 UTC, Luphia commented on src/api/gemini/gemini.module.ts
- use '@' for import path

2024-08-15 12:15 UTC, Luphia commented on src/api/gemini/gemini.service.spec.ts
- use '@' for import path

2024-08-15 12:15 UTC, Luphia commented on src/api/gemini/gemini.service.ts
- Annotation should be comply with the annotation format guidelines

2024-08-15 12:15 UTC, Luphia commented on src/api/gemini/gemini.controller.ts
- Annotation should be comply with the annotation format guidelines

2024-08-16 02:33 UTC, TinyMurky commented on src/api/gemini/gemini.controller.ts
修改完成！

2024-08-16 02:34 UTC, TinyMurky commented on src/api/gemini/gemini.module.ts
修改完成！

2024-08-16 02:34 UTC, TinyMurky commented on src/api/gemini/gemini.service.spec.ts
修改完成！

2024-08-16 02:34 UTC, TinyMurky commented on src/api/gemini/gemini.service.ts
修改完成！

2024-08-16 06:27 UTC, Luphia approved these changes
- no bug found

2024-08-16 06:27 UTC, merged